extensions:
  flagbit-menu-settings-product-category-config:
    module: pim/menu/item
    parent: pim-menu-settings-navigation-block
    aclResourceId: pim_enrich_product_category_list
    position: 121
    config:
      title: flagbit_category.entity.category_config.plural_label
      to: flagbit_category.entity.category_config

  flagbit-config-index-breadcrumbs:
    module: pim/common/breadcrumbs
    parent: flagbit-config-index
    targetZone: breadcrumbs
    config:
      tab: pim-menu-settings
      item: flagbit-menu-settings-product-category-config

  # form builder used in controller
  flagbit-config-index:
    module: pim/common/simple-view
    config:
      template: pim/template/common/default-template
