config:
  paths:
    flagbit-category/property/property-forms-renderer: flagbitcategory/js/property/property-forms-renderer
    flagbit-category/property/config-forms-renderer: flagbitcategory/js/property/config-forms-renderer

  config:
    pim/controller-registry:
      controllers:
        flagbit_category.entity.category_config:
          module: flagbit-category/property/config-forms-renderer
          aclResourceId: pim_enrich_product_category_list
          config:
            form_builder_name: "flagbit-config-index"
    pim/fetcher-registry:
      fetchers:
        default: 'pim/base-fetcher'
        flagbit-category-property:
          module: 'pim/base-fetcher'
          options:
            urls:
              get: 'flagbit_category.internal_api.category_property_get'
        flagbit-category-config:
          module: pim/base-fetcher
          options:
            urls:
              get: 'flagbit_category.internal_api.category_config_get'

    flagbitcategory/js/property/property-registry:
      text:
        type: '@flagbitcategory/js/property/type/text.tsx'
        config: '@flagbitcategory/js/property/type-config/base.tsx'
