parameters:
  pim_enrich.view_element.category.tab.property.template: 'FlagbitCategoryBundle:CategoryTree:Tab/property.html.twig'

services:
  Flagbit\Bundle\CategoryBundle\Controller\:
    resource: '../../../src/Controller/'
    bind:
      Flagbit\Bundle\CategoryBundle\Repository\CategoryConfigRepository: '@flagbit.category.repository.category_config'
      Flagbit\Bundle\CategoryBundle\Repository\CategoryPropertyRepository: '@flagbit.category.repository.category_property'
      Akeneo\Tool\Component\Classification\Repository\CategoryRepositoryInterface: '@pim_catalog.repository.category'
      Symfony\Component\Serializer\Normalizer\NormalizerInterface: '@pim_internal_api_serializer'
      Flagbit\Bundle\CategoryBundle\Schema\SchemaValidator: '@flagbit.category.schema.config_validator'
    autowire: true
    tags: [ 'controller.service_arguments' ]

  flagbit.category.repository.category_property:
    class: 'Flagbit\Bundle\CategoryBundle\Repository\CategoryPropertyRepository'
    factory: 'doctrine.orm.entity_manager:getRepository'
    arguments: [ 'Flagbit\Bundle\CategoryBundle\Entity\CategoryProperty' ]

  flagbit.category.repository.category_config:
    class: 'Flagbit\Bundle\CategoryBundle\Repository\CategoryConfigRepository'
    factory: 'doctrine.orm.entity_manager:getRepository'
    arguments: [ 'Flagbit\Bundle\CategoryBundle\Entity\CategoryConfig' ]

  flagbit.category.normalizer.object:
    class: 'Flagbit\Bundle\CategoryBundle\Serializer\Normalizer\ObjectNormalizer'
    arguments:
      - '@serializer.normalizer.object'
    tags:
      - { name: 'pim_internal_api_serializer.normalizer' }

  flagbit.category.property_values_bag:
    class: 'Symfony\Component\HttpFoundation\ParameterBag'

  flagbit.category.properties_bag:
    class: 'Symfony\Component\HttpFoundation\ParameterBag'

  flagbit.category.event_listener.collect_property_values:
    class: 'Flagbit\Bundle\CategoryBundle\EventListener\CollectPropertyValuesListener'
    arguments: [ '@flagbit.category.property_values_bag' ]
    tags:
      - { name: 'kernel.event_listener', event: 'kernel.controller_arguments' }

  flagbit.category.event_listener.bulk_save_property:
    class: 'Flagbit\Bundle\CategoryBundle\EventListener\BulkSavePropertyListener'
    arguments:
      - '@flagbit.category.properties_bag'
      - '@flagbit.category.repository.category_property'
      - '@doctrine.orm.entity_manager'
    tags:
      - { name: 'kernel.event_listener', event: 'akeneo.storage.post_save_all', method: 'onBulkCategoryPostSave' }

  flagbit.category.event_listener.save_property:
    class: 'Flagbit\Bundle\CategoryBundle\EventListener\SavePropertyListener'
    arguments:
      - '@flagbit.category.property_values_bag'
      - '@flagbit.category.repository.category_property'
      - '@doctrine.orm.entity_manager'
      - '@flagbit.category.schema.property_validator'
    tags:
      - { name: 'kernel.event_listener', event: 'akeneo.storage.post_save', method: 'onCategoryPostSave' }

  flagbit.category.converter.standard_to_flat.category_property:
    class: 'Flagbit\Bundle\CategoryBundle\Connector\ArrayConverter\StandardToFlat\CategoryProperty'

  flagbit.category.processor.normalization.category:
    class: 'Flagbit\Bundle\CategoryBundle\Connector\Processor\Normalization\ProcessorDecorator'
    decorates: 'pim_connector.processor.normalization.category'
    decoration_inner_name: 'flagbit.category.processor.normalization.category.inner'
    arguments:
      - '@flagbit.category.repository.category_property'
      - '@flagbit.category.converter.standard_to_flat.category_property'
      - '@flagbit.category.processor.normalization.category.inner'

  flagbit.category.array_converter.flat_to_standard.category:
    class: 'Flagbit\Bundle\CategoryBundle\Connector\ArrayConverter\FlatToStandard\CategoryDecorator'
    decorates: 'pim_connector.array_converter.flat_to_standard.category'
    decoration_inner_name: 'flagbit.category.array_converter.flat_to_standard.category.inner'
    arguments:
      - '@flagbit.category.array_converter.flat_to_standard.category.inner'
      - '@flagbit.category.properties_bag'

  flagbit.category.schema.property_validator:
    class: 'Flagbit\Bundle\CategoryBundle\Schema\SchemaValidator'
    arguments:
      - '../Resources/config/schema/property.json'

  flagbit.category.schema.config_validator:
    class: 'Flagbit\Bundle\CategoryBundle\Schema\SchemaValidator'
    arguments:
      - '../Resources/config/schema/config.json'
