name: "Backend Tests"

on:
  push: ~
  pull_request: ~
  schedule:
    - cron: "0 0 1 * *"

jobs:
  backend:
    runs-on: "ubuntu-20.04"
    strategy:
      matrix:
        php-versions: ['7.4']

    steps:
      - uses: "actions/checkout@v2.0.0"

      - name: "Setup PHP Action"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-versions }}"
          extensions: "intl, xdebug, imagick, apcu"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"
        with:
          composer-options: "--prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"

      # CI
      - name: "PHPSpec"
        run: "vendor/bin/phpspec run"

      - name: "Integration tests"
        run: "vendor/bin/phpunit"

      - name: "Upload coverage file"
        uses: "actions/upload-artifact@v2"
        with:
          name: "phpspec-${{ matrix.php-versions }}.coverage"
          path: "build/coverage.xml"

  coverage-upload:
    name: "Upload coverage to Codecov"
    runs-on: "ubuntu-20.04"

    needs:
      - "backend"

    steps:
      - uses: "actions/checkout@v2"

      - name: "Download coverage files"
        uses: "actions/download-artifact@v2"
        with:
          path: "reports"

      - name: "Upload to Codecov"
        uses: "codecov/codecov-action@v1"
        with:
          directory: "reports"
          flags: "backend"
