name: "Frontend Code Analysis + Style"

on:
  - "push"
  - "pull_request"

jobs:
  frontend:
    runs-on: "ubuntu-18.04"
    strategy:
      matrix:
        php-versions: [ '7.4' ]

    steps:
      - uses: "actions/checkout@v2.0.0"

      - name: "Setup PHP Action"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-versions }}"
          extensions: "intl, xdebug, imagick, apcu"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"
        with:
          composer-options: "--prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"

      - name: "yarn install"
        uses: "borales/actions-yarn@v2.0.0"
        with:
          cmd: "install"

      - name: "Check for obsolete ts exports"
        run: "yarn ts-unused-exports tsconfig.json $(find src/Resources/public -name '*.ts*') --showLineNumber"

      - name: "Typescript linting"
        run: "yarn tslint src/Resources/public/**/*{.ts,.tsx} src/Resources/public/**/**/*{.ts,.tsx} jest/**/*{.ts,.tsx}"

      - name: "Coding Style"
        #  jest/**/*{.ts,.tsx}
        run: "yarn prettier --config .prettierrc.json --check src/Resources/public/**/*{.ts,.tsx} jest/**/*.ts jest/**/*{.ts,.tsx}"
