name: "Frontend Tests"

on:
  push: ~
  pull_request: ~
  schedule:
    - cron: "0 0 1 * *"

jobs:
  frontend:
    runs-on: "ubuntu-18.04"
    strategy:
      matrix:
        php-versions: [ '7.4' ]

    steps:
      - uses: "actions/checkout@v2"

      - name: "Setup PHP Action"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-versions }}"
          extensions: "intl, xdebug, imagick, apcu"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"
        with:
          composer-options: "--prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"

      - name: "yarn install"
        uses: "borales/actions-yarn@v2.0.0"
        with:
          cmd: "install"

      - name: "Frontend tests"
        run: "yarn jest --no-cache --config jest.config.js --collect-coverage --collectCoverageFrom=src/**"

      - name: "Upload coverage file"
        uses: "actions/upload-artifact@v2"
        with:
          name: "jest.coverage"
          path: "build/clover.xml"

  coverage-upload:
    name: "Upload coverage to Codecov"
    runs-on: "ubuntu-18.04"

    needs:
      - "frontend"

    steps:
      - uses: "actions/checkout@v2"

      - name: "Download coverage files"
        uses: "actions/download-artifact@v2"
        with:
          path: "reports"

      - name: "Upload to Codecov"
        uses: "codecov/codecov-action@v1"
        with:
          directory: "reports"
          flags: "frontend"
